# ==========================================================
# User/environment specific settings
# ==========================================================
# Use privileged VMs in order to use tools like virt-manager on the host
# this also makes VMs survive reboots \o/
# Comment these if you want the unprivileged mode instead
non_root_chown: true
non_root_user: stack
undercloud_user: stack
working_dir: "/home/{{non_root_user}}"
ssh_user: root
libvirt_uri: qemu:///system

# ==========================================================
# Quickstart config for openstack/openshift testing
# Enables a basic containerized overcloud with network isolation
# ==========================================================

extra_args: >-
  --ntp-server pool.ntp.org

# This config is extremely resource intensive, so we disable telemetry
# in order to reduce the overall memory footprint
# This is not required in newton
telemetry_args: >-
   {% if release != 'newton' %}
   -e {{ overcloud_templates_path }}/environments/disable-telemetry.yaml
   {% endif %}
# Also disable telemetry on the undercloud
# This is needed until https://review.openstack.org/#/c/538872/ lands
undercloud_enable_telemetry: false

network_isolation: true
network_isolation_type: 'single-nic-vlans'

containerized_overcloud: true
containerized_undercloud: true
delete_docker_cache: false

ctlplane_masquerade: true

# Even though SSL isn't enabled for the overcloud we need
# undercloud_generate_service_certificate or the UI doesn't work
# FIXME(shardy) haproxy has ssl related errors so for now disable this
# and the UI
undercloud_enable_ui: true
undercloud_generate_service_certificate: true # true when using UI
ssl_overcloud: false
